Feature/developer
Al-Fro/task_manager pull request #18
Opened 2020-05-11 12:09 UTC by Al-Fro

2020-05-11 13:01 UTC, Al-Fro commented
создал новый PR, так как в прошлом (https://github.com/Al-Fro/task_manager/pull/14 после исправления замечаний попали исправления рубокопа). Подумал, что исправлять трудозатратно и бессмысленно, поэтому создал новый с  мержем ветки feature/developer с последними актуальными изменениями.

2020-05-11 18:55 UTC, pn-y requested changes

2020-05-11 18:55 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_response :success
Все точно работает правильно? У тебя тут https://github.com/Al-Fro/task_manager/pull/18/files#diff-e8160a277d748c3f508e97f9a461299fR11 редирект, а ты проверяешь на 200.
А еще ты не проверяешь суть™. Пользователь то создался или нет? При текущем тесте - экшон с одной строчкой `head 200` будет проходить этот тест. Что не хорошо

2020-05-12 13:11 UTC, pn-y requested changes

2020-05-12 13:11 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_not_nil new_developer
Бесполезная проверка. Ты проверяешь что factory bot работает? Ты же этого девелопера создал на 10 строчке сам.

2020-05-12 13:11 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_not_empty attrs[:first_name]
Бесполезная проверка. Ты же сам обьявил этот хеш на 11 строке

2020-05-12 15:50 UTC, pn-y requested changes

2020-05-12 15:50 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    current_user = Developer.where(email: attrs[:email])
find_by! вместо where
плюс вызов судя по логике должен быть после отправки запроса. Сейчас работает из-за ленивости

2020-05-12 15:50 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_equal attrs[:email], current_user[0]['email']
current_user[0] выглядит... абсолютно не семантично

2020-05-12 16:53 UTC, pn-y requested changes
в чяте расписал

2020-05-12 17:14 UTC, pn-y approved these changes

2020-05-12 21:27 UTC, merged