Feature/admin
Al-Fro/task_manager pull request #20
Opened 2020-05-15 08:53 UTC by Al-Fro

в фабрике task удален атрибут state, так как state берется initial из state_machines

2020-05-15 11:20 UTC, pn-y requested changes

2020-05-15 11:20 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +  setup do
в самое начало перенеси

2020-05-15 15:28 UTC, pn-y requested changes

2020-05-15 15:28 UTC, pn-y commented on app/controllers/admin/users_controller.rb
> +      render :new_admin_user_url
Мне кажется это не работает

2020-05-16 16:16 UTC, pn-y requested changes

2020-05-16 16:16 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
текс. Выглядит не правильно.
>class Admin::UsersControllerTest
>test/controllers/admin_controller_test.rb
Положи в правильное место этот код :)

2020-05-16 16:48 UTC, Al-Fro commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
перенес. только по логике мне кажется было бы логичнее иметь директорию юзерс, а в ней админ контроллер как тип юзера? а получается как то наоборот

2020-05-16 16:49 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
Отнюдь. Admin это неймспейс для админских вещей. И это первостепенно

2020-05-16 16:51 UTC, Al-Fro commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
понял, принял

2020-05-16 16:52 UTC, pn-y approved these changes

2020-05-16 16:55 UTC, merged