Feature/task
Al-Fro/task_manager pull request #24
Opened 2020-06-02 16:44 UTC by Al-Fro

2020-06-02 16:50 UTC, Al-Fro commented on .vscode/settings.json
> +  }
этого файла не должно быть, я его добавил в гитигнор, убрать из ПР?

2020-06-03 11:35 UTC, pn-y requested changes

2020-06-03 11:35 UTC, pn-y commented on .vscode/settings.json
> +  }
Если ты его добавил в гитигнор - его тут не должно быть, а должно быть обновление .gitignore

2020-06-03 11:35 UTC, pn-y commented on app/javascript/packs/components/TaskBoard/TaskBoard.js
> +        const newMeta = data.meta;
Какие то сложности получились.
Зачем тебе манипуляции с метой?
Свежая мета полностью актуальна, ее не надо модифицировать.

2020-06-03 11:35 UTC, pn-y commented on app/javascript/repositories/TasksRepository.js
> +  update(id, task = {}) {
Не нужны дефолтные значения. Они скрывают собой ошибку

2020-06-04 09:25 UTC, Al-Fro commented on app/javascript/packs/components/TaskBoard/TaskBoard.js
> +        const newMeta = data.meta;
переделал

2020-06-04 10:29 UTC, pn-y requested changes

2020-06-04 10:29 UTC, pn-y commented on app/javascript/packs/components/TaskBoard/TaskBoard.js
> +import AddPopup from '../AddPopup';
Кажется у тебя что-то пошло не так с файловой структурой. 
Например, если AddPopup используется только в TaskBoard - он должен быть внутри нее.

2020-06-04 11:02 UTC, Al-Fro commented on app/javascript/packs/components/TaskBoard/TaskBoard.js
> +import AddPopup from '../AddPopup';
тогда по логике все будет в taskboard, исправил

2020-06-05 12:14 UTC, pn-y approved these changes

2020-06-05 14:58 UTC, merged