Feature/assignee
Al-Fro/task_manager pull request #27
Opened 2020-06-06 19:12 UTC by Al-Fro

2020-06-07 07:41 UTC, vdv73rus commented on app/javascript/repositories/UsersRepository.js
> +  show(id) {
Не нашёл использования этого метода. Он точно нужен?

2020-06-07 12:43 UTC, Al-Fro commented on app/javascript/repositories/UsersRepository.js
> +  show(id) {
В данный момент этот метод вроде как не используется. Я его добавил, потому что в задании https://learn.dualboot.ru/lessons/10/practice/2 указан этот метод для контроллера юзера.

2020-06-11 15:36 UTC, helmq requested changes

2020-06-11 15:36 UTC, helmq commented on app/javascript/packs/components/TaskBoard/Form/Form.js
>  };
В propTypes для таски тоже нужно использовать презентер

2020-06-11 15:36 UTC, helmq commented on app/javascript/presenters/TaskPresenter.js
> +  author: PropTypes.string,
author и assignee точно строки?

2020-06-11 15:36 UTC, helmq commented on lib/js_routes/js_routes.rake
> +namespace :js_routes do
дубликат?

2020-06-11 15:36 UTC, helmq commented on config/webpacker.yml
> +  resolved_paths: ['app/presenters']
Это странно, что приходится указывать отдельные пути для презентеров

2020-06-12 12:02 UTC, Al-Fro commented on config/webpacker.yml
> +  resolved_paths: ['app/presenters']
убрал, он тут не нужен

2020-06-12 12:22 UTC, Al-Fro commented on lib/js_routes/js_routes.rake
> +namespace :js_routes do
чет напортачил, убрал

2020-06-12 12:23 UTC, Al-Fro commented on lib/js_routes/js_routes.rake
> +namespace :js_routes do
убрал

2020-06-12 12:48 UTC, helmq approved these changes

2020-06-12 13:38 UTC, merged