Feature/coveralls
Al-Fro/task_manager pull request #30
Opened 2020-06-09 13:39 UTC by Al-Fro

2020-06-09 16:25 UTC, Al-Fro commented on .travis.yml
> +  - docker-compose run --rm web /bin/sh -c "RAILS_ENV=test TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_BRANCH=$TRAVIS_BRANCH  bundle exec coveralls report"
у меня возникло подозрение, что я сделал неправильно. Потому что бейджик не отображает результат работы coveralls. Я думаю, это из-за того, что coveralls работает в контейнере, но прокинуть значения у меня никак не получилось. Жду проверки

2020-06-12 13:50 UTC, pn-y requested changes

2020-06-12 13:50 UTC, pn-y commented on .travis.yml
> +  - docker-compose run --rm web /bin/sh -c "RAILS_ENV=test TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_BRANCH=$TRAVIS_BRANCH  bundle exec coveralls report"
Без телепатов не разобраться. Пиши что не так etc.

2020-06-15 21:00 UTC, pn-y requested changes

2020-06-15 21:00 UTC, pn-y commented on README.md
> +[![Build Status](https://travis-ci.com/Al-Fro/task_manager.svg?branch=feature%2Ftravis)](https://travis-ci.com/Al-Fro/task_manager)    [![Coverage Status](https://coveralls.io/repos/github/Al-Fro/tas
Кмк оно должно на девелоп ссылаться, ведь эта ветка с большой долей вероятности потратиться после мержа

2020-06-16 15:32 UTC, pn-y approved these changes

2020-06-19 16:07 UTC, merged