Feature/add files
Al-Fro/task_manager pull request #36
Opened 2020-06-30 15:57 UTC by Al-Fro

2020-06-30 20:18 UTC, pn-y requested changes

2020-06-30 20:18 UTC, pn-y commented on Dockerfile
> +RUN apk --update add imagemagick
Еще один слой создастся, совсем не нужный. Добавь imagemagick в 4 строку

2020-06-30 20:18 UTC, pn-y commented on db/schema.rb
> +    t.string "password_reset_token"
эти изменения из другого МР

2020-07-01 06:09 UTC, Al-Fro commented on db/schema.rb
> +    t.string "password_reset_token"
пропустил.. Откатил как надо

2020-07-06 21:41 UTC, artempartos approved these changes

2020-07-07 13:12 UTC, merged