Feature/models
Al-Fro/task_manager pull request #6
Opened 2020-04-27 13:28 UTC by Al-Fro

2020-04-28 12:03 UTC, pn-y requested changes

2020-04-28 12:03 UTC, pn-y commented on test/factories/tasks.rb
> +    author_id { 1 }
Если можно не опускаться до уровня something_id - не стоит этого делать.

Factory Bot умеет работать с ассоциациями как с сущностями.

Но их не стоит создавать каждый раз - сделай их пустыми. Это нужно для того что бы не создавалось по 100500 сущностей при вызове фабрики.

Сделай отдельные трейты где бы создавался auther или assignee

2020-04-28 12:03 UTC, pn-y commented on test/factories/tasks.rb
> +    description { "MyText" }
Используй sequence для таких текстовых полей

2020-04-28 12:03 UTC, pn-y commented on test/factories/users.rb
> +    type { "" }
Пустой тип - не валидные данные

2020-05-04 16:59 UTC, Andrew8xx8 requested changes

2020-05-04 16:59 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
Пустые тесты надо удалить

2020-05-06 11:06 UTC, Al-Fro commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
тесты удалил, пустые фабрики тоже надо удалить, пока не используются?

2020-05-08 16:34 UTC, closed without merging